name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.spec.name }}
    runs-on: ${{ matrix.spec.runner }}
    container:
      image: ${{ matrix.spec.builder }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { name: 'Windows x86_64', runner: 'windows-2022', target: 'windows-x64', test: 'true' }
    steps:
      - name: Add msbuild to PATH
        if: startsWith(matrix.spec.runner, 'windows')
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run build for ${{ matrix.spec.target }}
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.spec.target }}
          test: ${{ matrix.spec.test }}
          test_id: ${{ secrets.ZITI_TEST_IDENTITY }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ziti-prox-c-${{ matrix.spec.target }}
          path: ./build/programs/ziti-prox-c/**/ziti-prox-c*.zip

      - name: upload SDK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ziti-sdk-${{ matrix.spec.target }}
          path: ./build/package/ziti-sdk-*
